### ISSUE TITLE
Stuttering after long sessions

### ISSUE THREAD

**Issue by Zeralit** [adamk33n3r/runelite-watchdog#75]
Hello, I have had a problem for a few months now and unfortunately I think it comes from this plugin. After spending several hours mining (anywhere between 4 hours to 6 is where it starts), the game will eventually begin to stutter really bad when using custom sound effects.
The log has been attached, however this is the only part I think is relevant. It is repeated many times throughout. Can provide a Heap Dump file too if necessary.

```
2023-06-28 23:37:13 CEST [ForkJoinPool.commonPool-worker-9] WARN  c.a.r.watchdog.notifications.Sound - Unable to load sound
java.io.IOException: Audio data is too big
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(Unknown Source)
	at com.adamk33n3r.runelite.watchdog.notifications.Sound.tryPlaySound(Sound.java:58)
	at com.adamk33n3r.runelite.watchdog.notifications.Sound.lambda$fireImpl$0(Sound.java:41)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
2023-06-28 16:40:02 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.adamk33n3r.runelite.watchdog.EventHandler.onTileObjectSpawned(EventHandler.java:357)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onGameObjectSpawned(EventHandler.java:338)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:191)
	at iz.ru(iz.java:3595)
	at client.tn(client.java:3407)
	at client.jy(client.java:14401)
	at client.hi(client.java:3109)
	at client.bn(client.java:1139)
	at ba.al(ba.java:382)
	at ba.run(ba.java:361)
	at java.base/java.lang.Thread.run(Unknown Source)
```
[client.log](https://github.com/adamk33n3r/runelite-watchdog/files/11900166/client.log)

**Comment by adamk33n3r** [comment]
the NPE is related to tile objects and I'm not sure how it could be null, maybe I need to be checking for a `-1` object id or something.

as for the audio data too big exception, that ones for custom sounds (like a wav file), not sound effects. I didn't realize there was a size limit, but it seems that the sound clip you're trying to use is too large. Do you know what the size is?

**Comment by Zeralit** [comment]
0.45 KB
1,83 MB
and 1,68 MB

All of them .wav files

**Comment by adamk33n3r** [comment]
Hm...I wonder if there's a memory leak of some kind. I'll look into it.

**Comment by adamk33n3r** [comment]
Looking at your log more closely, it looks like you started up RuneLite at 23:28, and started getting the exceptions at 23:33. So only 5 minutes. Do you know if it was playing a lot in those 5 minutes? I discovered that I'm not calling `clip.close()` after the sound is done playing, which is bad. I'm not 100% sure it will solve the "audio data is too big" issue, but I'm curious to try.

**Comment by adamk33n3r** [comment]
Also, I watched my task manager while I spammed the test button on a custom sound and did notice the ram usage increase. So it was indeed a memory leak.
